models:
  - type: main
    engine: openai
    model: gpt-4o-mini

rails:
  input:
    flows: []
  
  dialog:
    flows:
      - discovery
      - hello_world
  
  output:
    flows: []

config:
  flow_logging:
    enabled: true
